// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPG9EBidhAxjvMD3nTjneE-3VitAdmGM',
    appId: '1:970305362077:android:1efe59fbffc0f69af09c74',
    messagingSenderId: '970305362077',
    projectId: 'qaproject-351eb',
    storageBucket: 'qaproject-351eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5C6sNbkmkLMwi8v_qq3y97F6cS3Dtzw',
    appId: '1:970305362077:ios:09a20593348ec88bf09c74',
    messagingSenderId: '970305362077',
    projectId: 'qaproject-351eb',
    storageBucket: 'qaproject-351eb.appspot.com',
    androidClientId: '970305362077-3e5bp29ahiipvmhpf9ajaob98m3ht00g.apps.googleusercontent.com',
    iosClientId: '970305362077-auo0hoe5q6rd7glphcs0htfvg62sfjre.apps.googleusercontent.com',
    iosBundleId: 'com.example.testqa',
  );
}
